### ISSUE TITLE
调用删除图片方法出现的问题

### ISSUE THREAD

**Issue by jacky-zeng** [overtrue/laravel-filesystem-qiniu#14]
$disk = Storage::disk('qiniu');
$rs   = $disk->delete($file_name);
使用上面的方法进行删除图片，调用后，返回true,再传相同的文件名，调用后返回false,说明方法没问题，但是去浏览器里访问这个图片的url，还是能访问到，没删除？

**Comment by overtrue** [comment]
CDN 删除文件需要一定的时间的哦
