### ISSUE TITLE
laravel5.4 listContents()返回为空

### ISSUE THREAD

**Issue by bilwy** [overtrue/laravel-filesystem-qiniu#2]
vendor/overtrue/flysystem-qiniu/src/QiniuAdapter.php
 public function listContents()
return:

array (
  0 => 
  array (
    'type' => 'file',
    'path' => 'cover/2017/06/30/7D46QkBNnePJoswZQXqYseM08vJq9tsZXssT9DrX.jpg',
    'timestamp' => 1498816002.0,
    'size' => 51519,
  ),
  1 => 
  array (
    'type' => 'file',
    'path' => 'cover/2017/07/01/xUNgtbp2i5nWyhuSmM3EfIyuTd85hC4SqsSnVPH9.jpg',
    'timestamp' => 1498880783.0,
    'size' => 82849,
  ),
)

public function disk()
    {
        $disk = Storage::disk('qiniu');
        $list = $disk->listContents();
        dd($list);
    }
[]

**Comment by overtrue** [comment]
请升级到 1.0
