### ISSUE TITLE
无法列出目录

### ISSUE THREAD

**Issue by shellus** [overtrue/laravel-filesystem-qiniu#23]
使用listContents()方法只能列出文件，无法列出目录

**Comment by overtrue** [comment]
https://github.com/qiniu/php-sdk/blob/master/src/Qiniu/Storage/BucketManager.php 官方 SDK 不支持哇

<blockquote><img src="https://avatars3.githubusercontent.com/u/1563636?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/qiniu/php-sdk">qiniu/php-sdk</a></strong></div><div>Qiniu Resource (Cloud) Storage SDK for PHP. Contribute to qiniu/php-sdk development by creating an account on GitHub.</div></blockquote>
