### ISSUE TITLE
 Trying to get property 'srcUpHosts' of non-object

### ISSUE THREAD

**Issue by dahaigit** [overtrue/laravel-filesystem-qiniu#24]
error_reporting | Trying to get property 'srcUpHosts' of non-object
-- | --
line | 48
code | 8
file | .../api/vendor/qiniu/php-sdk/src/Qiniu/Config.php

**Comment by overtrue** [comment]
检查你的配置 region 项：

https://github.com/qiniu/php-sdk/blob/master/src/Qiniu/Config.php#L48

<blockquote><img src="https://avatars3.githubusercontent.com/u/1563636?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/qiniu/php-sdk">qiniu/php-sdk</a></strong></div><div>Qiniu Resource (Cloud) Storage SDK for PHP. Contribute to qiniu/php-sdk development by creating an account on GitHub.</div></blockquote>
