### ISSUE TITLE
升级qiniuSDK v7.2.0后报错,,回到v7.1.3好了 

### ISSUE THREAD

**Issue by numbersi** [overtrue/laravel-filesystem-qiniu#3]
![qq 20170823193240](https://user-images.githubusercontent.com/11460226/29613711-dd3b49d4-8839-11e7-987c-b41eda2d555a.jpg)
 

php artisan  backup:run

Starting backup...
Dumping database kuainiaoyaofei...
Determining files to backup...
Zipping 692 files...
Created zip containing 692 files. Size is 4.47 MB
Copying zip to disk named qiniu...
from query

Successfully copied zip to disk named qiniu.
Copying zip failed because: Undefined index: key.
Backup failed because Undefined index: key.
#0 /var/www/kuainiao/vendor/overtrue/flysystem-qiniu/src/QiniuAdapter.php(476): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/kuaini...', 476, Array)

**Comment by overtrue** [comment]
能不能麻烦你看看在 新版本的时候那个 
![image](https://user-images.githubusercontent.com/1472352/29615396-67c3b252-8840-11e7-91ab-98013e03fa7f.png) 地方的 Array 是一个什么样的内容，记一下日志看看。

**Comment by overtrue** [comment]
https://github.com/overtrue/flysystem-qiniu/commit/eb23eacfd709efeeafccb38474238564986ed9d7
