### ISSUE TITLE
How to create upload token

### ISSUE THREAD

**Issue by smartyaunt** [overtrue/laravel-filesystem-qiniu#4]
HI, Help Me How to create upload token

**Comment by overtrue** [comment]
请升级到 1.0 直接就可以用 `$disk->getUploadToken('stardust.png');` 拿到了 `stardust.png` 请换成你的文件

**Comment by smartyaunt** [comment]
是上传文件使用的token，这个好像不是吧！

**Comment by smartyaunt** [comment]
如果是多文件上传，又该怎么处理呢，求助大神

**Comment by overtrue** [comment]
@smartyaunt 上传用的 token 你直接使用 官方 SDK 提供的 API 吧

**Comment by overtrue** [comment]
多文件上传也得一个个传
